console.log(false && false);
console.log(false && true);
console.log(true && false);
console.log(true && true);
console.log();
console.log(false || false);
console.log(false || true);
console.log(true || false);
console.log(true || true);
console.log();
console.log(!false);
console.log(!true);